import re

base_url = 'https://sede.administracionespublicas.gob.es'
#base_url = 'http://127.0.0.1:5000'  # for local simulation
no_cita_message = 'En este momento no hay citas disponibles.'
error_503_message = 'ERROR [503]'
nie_pattern = re.compile(r'^[XYZ]\d{7,8}[A-Z]$')
hidden_params_pattern = re.compile(
    r'><input type="hidden" name="([\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12})" value(?:="([\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12})")?/><input type="hidden" name="([\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12})" value(?:="([\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12})")?/>')
offices_pattern = re.compile(r'<option value="(\d+)"\s?>(.+)</option>')
cita_pattern = re.compile(
    r'<span>CITA</span>\s*(\d+)[\s\S]+?Día</span>: <span>(\d{2}/\d{2}/\d{4})</span> <br(?: /)?> <span>Hora</span>: <span>(\d{2}:\d{2})</span> <br')
cita_code_pattern = re.compile(r'<span id="justificanteFinal" class="mf-carousel--item-title">([\dA-Z]+?)</span>')

browser_headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36',
    'Cache-Control': 'no-cache',
    # 'Accept-Language': 'en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,ca-ES;q=0.6,ca;q=0.5',
    # 'Accept-Encoding': 'gzip, deflate',
    # 'Referer': f'{base_url}/icpplus/index.html',
    # 'DNT': '1',
    # 'sec-ch-ua': '"Google Chrome";v="95", "Chromium";v="95", ";Not A Brand";v="99"',
    # 'sec-ch-ua-mobile': '?0',
    # 'sec-ch-ua-platform': '"Windows"',
    # 'Upgrade-Insecure-Requests': '1',
    # 'Sec-Fetch-Site': 'same-origin',
    # 'Sec-Fetch-Mode': 'navigate',
    # 'Sec-Fetch-User': '?1',
    # 'Sec-Fetch-Dest': 'document',
}

countries = {
    'AFGANISTAN': 401,
    'ALBANIA': 102,
    'ALEMANIA': 103,
    'ANDORRA': 133,
    'ANGOLA': 301,
    'ANGUILLA': 258,
    'ANTIGUA Y BARBUDA': 255,
    'ANTILLAS NL.': 200,
    'APATRIDA': 600,
    'ARABIA SAUDI': 403,
    'ARGELIA': 304,
    'ARGENTINA': 202,
    'ARMENIA': 142,
    'ARUBA': 257,
    'AUSTRALIA': 500,
    'AUSTRIA': 104,
    'AZERBAYAN': 143,
    'BAHAMAS': 203,
    'BAHREIN': 405,
    'BANGLADESH': 432,
    'BARBADOS': 205,
    'BELGICA': 105,
    'BELICE': 207,
    'BENIN': 302,
    'BHUTAN': 407,
    'BIELORRUSIA O BELARUS': 144,
    'BOLIVIA': 204,
    'BOSNIA-HERZEGOVINA': 156,
    'BOTSWANA': 305,
    'BRASIL': 206,
    'BRUNEI DARUSSALAM': 409,
    'BULGARIA': 134,
    'BURKINA FASO': 303,
    'BURUNDI': 321,
    'CABO VERDE': 315,
    'CAMBOYA': 402,
    'CAMERUN': 308,
    'CANADA': 208,
    'CENTROAFRICA REPUBLICA': 310,
    'CHAD': 372,
    'CHILE': 210,
    'CHINA': 406,
    'CHIPRE': 107,
    'COLOMBIA': 212,
    'COMORES': 311,
    'CONGO BRAZZAVILLE': 312,
    'COREA, REP. POP. DEMOC.': 460,
    'COREA, REPUBLICA': 410,
    'COSTA DE MARFIL': 314,
    'COSTA RICA': 214,
    'CROACIA': 140,
    'CUBA': 216,
    'DINAMARCA': 108,
    'DJIBOUTI': 317,
    'DOMINICA': 217,
    'DOMINICANA REPUBLICA': 218,
    'ECUADOR': 222,
    'EEUU': 224,
    'EGIPTO': 300,
    'EL SALVADOR': 220,
    'EL VATICANO': 136,
    'EMIRATOS ARABES UNIDOS': 429,
    'ERITREA': 384,
    'ESLOVAQUIA': 158,
    'ESLOVENIA': 141,
    'ESPAÑA': 109,
    'ESTONIA': 137,
    'ETIOPIA': 318,
    'FIDJI': 550,
    'FILIPINAS': 411,
    'FINLANDIA': 110,
    'FRANCIA': 111,
    'GABON': 320,
    'GAMBIA': 323,
    'GEORGIA': 145,
    'GHANA': 322,
    'GRANADA REPUBLICA': 229,
    'GRECIA': 113,
    'GUATEMALA': 228,
    'GUAYANA': 225,
    'GUINEA ECUATORIAL': 324,
    'GUINEA REPUBLICA': 325,
    'GUINEA-BISSAU': 328,
    'HAITI': 230,
    'HOLANDA': 123,
    'HONDURAS': 232,
    'HUNGRIA': 114,
    'INDIA': 412,
    'INDONESIA': 414,
    'IRAK': 413,
    'IRAN': 415,
    'IRLANDA': 115,
    'ISLANDIA': 116,
    'ISLAS MARSCHALL': 520,
    'ISRAEL': 417,
    'ITALIA': 117,
    'JAMAICA': 233,
    'JAPON': 416,
    'JORDANIA': 419,
    'KAZAJSTAN': 146,
    'KENIA': 336,
    'KIRGUISTAN': 147,
    'KIRIBATI': 501,
    'KUWAIT': 421,
    'LAOS': 418,
    'LAS MALDIVAS': 436,
    'LESOTHO': 337,
    'LETONIA': 138,
    'LIBANO': 423,
    'LIBERIA': 342,
    'LIBIA': 344,
    'LIECHTENSTEIN': 118,
    'LITUANIA': 139,
    'LUXEMBURGO': 119,
    'MACAO': 463,
    'MACEDONIA': 159,
    'MADAGASCAR': 354,
    'MALASIA': 425,
    'MALASIA - GRAN BRETAÑA': 900,
    'MALAWI': 346,
    'MALI': 347,
    'MALTA': 120,
    'MARRUECOS': 348,
    'MAURICIO': 349,
    'MAURITANIA': 350,
    'MEJICO': 234,
    'MICRONESIA': 525,
    'MOLDAVIA': 148,
    'MONACO': 121,
    'MONGOLIA': 427,
    'MONTENEGRO': 160,
    'MOZAMBIQUE': 351,
    'MYANMAR': 400,
    'NAMIBIA': 353,
    'NAURU': 541,
    'NEPAL': 420,
    'NICARAGUA': 236,
    'NIGER': 360,
    'NIGERIA': 352,
    'NORUEGA': 122,
    'NUEVA ZELANDA': 540,
    'OMAN': 444,
    'PAKISTAN': 424,
    'PANAMA': 238,
    'PAPUA NUEVA GUINEA': 542,
    'PARAGUAY': 240,
    'PERU': 242,
    'POLONIA': 124,
    'PORTUGAL': 125,
    'PUERTO RICO': 244,
    'QATAR': 431,
    'REINO UNIDO': 112,
    'REP. DEMOCRATICA DEL CONGO (EX-ZAIRE)': 380,
    'REPUBLICA CHECA': 157,
    'REUNION-COMO': 355,
    'RUANDA': 306,
    'RUMANIA': 127,
    'RUSIA': 149,
    'SALOMON': 551,
    'SAMOA OCCIDENTAL': 552,
    'SAN CRISTOBAL Y NEVIS': 256,
    'SAN MARINO': 135,
    'SAN VICENTE': 254,
    'SANTA LUCIA': 253,
    'SANTO TOME Y PRINCIPE': 361,
    'SEICHELLES': 363,
    'SENEGAL': 362,
    'SENEGAMBIA': 366,
    'SERBIA': 155,
    'SIERRA LEONA': 364,
    'SINGAPUR': 426,
    'SIRIA': 433,
    'SOMALIA': 365,
    'SRI LANKA': 404,
    'SUDAFRICA': 367,
    'SUDAN': 368,
    'SUECIA': 128,
    'SUIZA': 129,
    'SURINAM': 250,
    'SWAZILANDIA': 371,
    'TADJIKISTAN': 154,
    'TAIWAN': 408,
    'TANZANIA': 370,
    'THAILANDIA': 428,
    'TIMOR ORIENTAL': 465,
    'TOGO': 374,
    'TONGA': 554,
    'TRINIDAD Y TOBAGO': 245,
    'TUNEZ': 378,
    'TURKMENIA': 151,
    'TURQUIA': 130,
    'TUVALU': 560,
    'UCRANIA': 152,
    'UGANDA': 358,
    'URUGUAY': 246,
    'UZBEKISTAN': 153,
    'VANUATU': 565,
    'VENEZUELA': 248,
    'VIETNAM': 430,
    'YEMEN': 434,
    'ZAMBIA': 382,
    'ZIMBABWE': 357,
}

tramites = {
    'POLICIA - RECOGIDA DE TARJETA DE IDENTIDAD DE EXTRANJERO (TIE)': 4036,
    'POLICIA-AUTORIZACIÓN DE REGRESO': 20,
    'POLICIA-TOMA DE HUELLAS (EXPEDICIÓN DE TARJETA) Y RENOVACIÓN DE TARJETA DE LARGA DURACIÓN': 4010,
    'POLICIA-CARTA DE INVITACIÓN': 4037,
    'POLICIA-CERTIFICADO DE REGISTRO DE CIUDADANO DE LA U.E.': 4038,
    'POLICIA-CERTIFICADOS (DE RESIDENCIA, DE NO RESIDENCIA Y DE CONCORDANCIA)': 4049,
    'POLICIA- EXPEDICIÓN/RENOVACIÓN DE DOCUMENTOS DE SOLICITANTES DE ASILO': 4067,
    'POLICIA- SOLICITUD ASILO': 4078,
    'POLICIA-CERTIFICADOS Y ASIGNACION NIE (NO COMUNITARIOS)': 4079,
    'POLICIA - TÍTULOS DE VIAJE': 4092,
    'POLICÍA-EXP.TARJETA ASOCIADA AL ACUERDO DE RETIRADA CIUDADANOS BRITÁNICOS Y SUS FAMILIARES (BREXIT)': 4094,
    'POLICIA-CERTIFICADOS Y ASIGNACION NIE': 4096,
}

office_codes = {
    'CNP CARTAS DE INVITACION, CALLE GUADALAJARA , 1': 48,
    'CNP COMISARIA BADALONA, AVDA. DELS VENTS, 9': 18,
    'CNP COMISARIA CASTELLDEFELS, PLAÇA DE L`ESPERANTO, 4': 19,
    'CNP COMISARIA CERDANYOLA DEL VALLES, VERGE DE LES FEIXES, 4': 20,
    'CNP COMISARIA CORNELLA DE LLOBREGAT, AV. SANT ILDEFONS, S/N': 21,
    'CNP COMISARIA EL PRAT DE LLOBREGAT, CENTRE, 4': 23,
    'CNP COMISARIA GRANOLLERS, RICOMA, 65': 28,
    'CNP COMISARIA IGUALADA, PRAT DE LA RIBA, 13': 26,
    'CNP COMISARIA LHOSPITALET DE LLOBREGAT, Rbla. Just Oliveres, 43': 17,
    'CNP COMISARIA MANRESA, SOLER I MARCH, 5': 38,
    'CNP COMISARIA MATARO, AV. GATASSA, 15': 27,
    'CNP COMISARIA MONTCADA I REIXAC, MAJOR, 38': 31,
    'CNP COMISARIA RIPOLLET, TAMARIT, 78': 32,
    'CNP COMISARIA RUBI, TERRASSA, 16': 29,
    'CNP COMISARIA SABADELL, BATLLEVELL, 115': 30,
    'CNP COMISARIA SANT ADRIA DEL BESOS, AV. JOAN XXIII, 2': 33,
    'CNP COMISARIA SANT BOI DE LLOBREGAT, RIERA BASTÉ, 43': 24,
    'CNP COMISARIA SANT CUGAT DEL VALLES, VALLES, 1': 34,
    'CNP COMISARIA SANT FELIU DE LLOBREGAT, CARRERETES, 9': 22,
    'CNP COMISARIA SANTA COLOMA DE GRAMENET, IRLANDA, 67': 35,
    'CNP COMISARIA TERRASSA, BALDRICH, 13': 36,
    'CNP COMISARIA VIC, BISBE MORGADES, 4': 37,
    'CNP COMISARIA VILADECANS, AVDA. BALLESTER, 2': 25,
    'CNP COMISARIA VILAFRANCA DEL PENEDES, Avinguda Ronda del Mar, 109': 46,
    'CNP COMISARIA VILANOVA I LA GELTRU, VAPOR, 19': 39,
    'CNP MALLORCA GRANADOS, MALLORCA, 213': 14,
    'CNP PSJ PLANTA BAJA, PASSEIG SANT JOAN, 189': 43,
    'CNP RAMBLA GUIPUSCOA 74, RAMBLA GUIPUSCOA, 74': 16,
    'OUE BCN-C/MURCIA, 42, MURCIA, 42': 5,
    'PASSEIG DE SANT JOAN, PASSEIG DE SANT JOAN, 189': 6,
}


class CountryNotFoundError(Exception):
    pass


class TramiteNotFoundError(Exception):
    pass


class FailedAttempt(Exception):
    pass


class FailedAttemptAtOffice(Exception):
    pass
